### PR TITLE
Fix https://github.com/tonsky/uberdeps/issues/2

### PR DESCRIPTION
**Pull request by jdf-id-au**
Reads META-INF/services/** files into memory as they're encountered (instead of copying straight to jar). Service files with same pathname are concatenated, then written to jar after `package-libs`.

### CODE REVIEW

**Comment by tonsky** [comment]
Thanks! Do you think anything should be done about files that have same name but in a different register? E.g. `META-INF/services/x` vs `META-INF/SERVICES/x` or `META-INF/services/X`?

**Comment by tonsky** [comment]
Ok lein doesn’t seem to do anything about it, and as far as I remember files are looked up in resources in case-sensitive way, so better not to be smart here. Thanks for the contribution!

**Comment by tonsky** [comment]
Pushed 0.1.11

**Comment by jdf-id-au** [comment]
Thank you for nice polish. Agree with case sensitivity, error on my part.

**Pull request merged**
