### PR TITLE
Fix no-config bash alias in readme

### PR DESCRIPTION
**Pull request by imrekoszo**
Proposes a fix for https://github.com/tonsky/uberdeps/issues/33

### CODE REVIEW

**Comment by tonsky** [comment]
Wouldn’t `clj -Sdeps '{:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -M -m uberdeps.uberjar` also work?

**Comment by imrekoszo** [comment]
That doesn't seem to work for me. [Official doc](https://clojure.org/reference/deps_and_cli#_replace_project_environment_tool) also says
> This tool map should be provided as an alias in one of the deps sources

**Comment by tonsky** [comment]
Didn’t work how? What version of Clojure command-line tool do you have?

```bash
[~/ws/uberdeps] clj -Sdeps '{:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -M -m uberdeps.uberjar
[uberdeps] Packaging target/uberdeps.jar...
...
```

**Comment by imrekoszo** [comment]
Sorry, I didn't have time yesterday to properly explain my point. In the name of reproducibility I'll be using the Kaocha project in the example, for the reasons of it being a deps.edn-based public project, with no references of its own to uberdeps.

```bash
git clone git@github.com:lambdaisland/kaocha.git && cd kaocha && git checkout faa6ef6027052793513e85713090306cb1842026
```

Also adding `-Srepro` so my user deps.edn isn't taken into account, and `-Sverbose` for version info.

Using `:replace-deps` at the root level:

```bash
> clj -Srepro -Sverbose -Sdeps '{:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -M -m uberdeps.uberjar
version      = 1.10.1.727
install_dir  = /usr/local/Cellar/clojure/1.10.1.727
config_dir   = /Users/ikoszo/.clojure
config_paths = /usr/local/Cellar/clojure/1.10.1.727/deps.edn deps.edn
cache_dir    = .cpcache
cp_file      = .cpcache/2543265959.cp

Refreshing classpath
DEPRECATED: Libs must be qualified, change aero => aero/aero (deps.edn)
DEPRECATED: Libs must be qualified, change orchestra => orchestra/orchestra (deps.edn)
DEPRECATED: Libs must be qualified, change slingshot => slingshot/slingshot (deps.edn)
DEPRECATED: Libs must be qualified, change meta-merge => meta-merge/meta-merge (deps.edn)
DEPRECATED: Libs must be qualified, change hawk => hawk/hawk (deps.edn)
DEPRECATED: Libs must be qualified, change progrock => progrock/progrock (deps.edn)
DEPRECATED: Libs must be qualified, change expound => expound/expound (deps.edn)
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate uberdeps/uberjar__init.class, uberdeps/uberjar.clj or uberdeps/uberjar.cljc on classpath.

Full report at:
/var/folders/yq/pzs9fnnj5g715j73kxglggcjtyvz55/T/clojure-6130300433733195331.edn
```

In the same folder, at the same commit, using `:replace-deps` in an alias:

```bash
> clj -Sverbose -Srepro -Sdeps '{:aliases {:uberjar {:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}}}' -M:uberjar -m uberdeps.uberjar
version      = 1.10.1.727
install_dir  = /usr/local/Cellar/clojure/1.10.1.727
config_dir   = /Users/ikoszo/.clojure
config_paths = /usr/local/Cellar/clojure/1.10.1.727/deps.edn deps.edn
cache_dir    = .cpcache
cp_file      = .cpcache/3374350669.cp

DEPRECATED: Libs must be qualified, change aero => aero/aero
DEPRECATED: Libs must be qualified, change orchestra => orchestra/orchestra
DEPRECATED: Libs must be qualified, change slingshot => slingshot/slingshot
DEPRECATED: Libs must be qualified, change meta-merge => meta-merge/meta-merge
DEPRECATED: Libs must be qualified, change hawk => hawk/hawk
DEPRECATED: Libs must be qualified, change progrock => progrock/progrock
DEPRECATED: Libs must be qualified, change expound => expound/expound
[uberdeps] Packaging target/kaocha.jar...
+ resources/**
+ src/**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
+ aero/aero #:mvn{:version "1.1.6"}
+ expound/expound #:mvn{:version "0.8.5"}
+ hawk/hawk #:mvn{:version "0.2.11"}
.   net.incongru.watchservice/barbary-watchservice #:mvn{:version "1.0"}
.     net.java.dev.jna/jna #:mvn{:version "3.2.2"}
+ lambdaisland/deep-diff #:mvn{:version "0.0-47"}
.   fipp/fipp #:mvn{:version "0.6.17"}
.     org.clojure/core.rrb-vector #:mvn{:version "0.0.14"}
.   mvxcvi/arrangement #:mvn{:version "1.2.0"}
.   mvxcvi/puget #:mvn{:version "1.1.2"}
-     skipping duplicate lib fipp/fipp #:mvn{:version 0.6.17}
-     skipping duplicate lib mvxcvi/arrangement #:mvn{:version 1.2.0}
-   skipping duplicate lib org.clojure/core.rrb-vector #:mvn{:version 0.0.14}
.   tech.droit/clj-diff #:mvn{:version "1.0.1"}
+ lambdaisland/tools.namespace #:mvn{:version "0.0-237"}
.   org.clojure/java.classpath #:mvn{:version "0.3.0"}
.   org.clojure/tools.reader #:mvn{:version "1.3.2"}
+ meta-merge/meta-merge #:mvn{:version "1.0.0"}
+ orchestra/orchestra #:mvn{:version "2020.07.12-1"}
+ org.clojure/clojure #:mvn{:version "1.10.1"}
.   org.clojure/core.specs.alpha #:mvn{:version "0.2.44"}
+ org.clojure/spec.alpha #:mvn{:version "0.2.187"}
+ org.clojure/tools.cli #:mvn{:version "1.0.194"}
+ org.tcrawley/dynapath #:mvn{:version "1.1.0"}
+ progrock/progrock #:mvn{:version "0.1.2"}
+ slingshot/slingshot #:mvn{:version "0.12.2"}
[uberdeps] Packaged target/kaocha.jar in 1038 ms
```

Looking at the dependency trees, first for `:replace-deps` at root level. Note that uberdeps is not included, only the Kaocha deps, which shows why the first call didn't work:

```bash
> clj -Srepro -Sverbose -Sdeps '{:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -Stree
version      = 1.10.1.727
install_dir  = /usr/local/Cellar/clojure/1.10.1.727
config_dir   = /Users/ikoszo/.clojure
config_paths = /usr/local/Cellar/clojure/1.10.1.727/deps.edn deps.edn
cache_dir    = .cpcache
cp_file      = .cpcache/2543265959.cp

org.clojure/clojure 1.10.1
  org.clojure/core.specs.alpha 0.2.44
expound/expound 0.8.5
org.clojure/spec.alpha 0.2.187
org.clojure/tools.cli 1.0.194
lambdaisland/deep-diff 0.0-47
  mvxcvi/puget 1.1.2
  fipp/fipp 0.6.17
  mvxcvi/arrangement 1.2.0
  org.clojure/core.rrb-vector 0.0.14
  tech.droit/clj-diff 1.0.1
slingshot/slingshot 0.12.2
aero/aero 1.1.6
lambdaisland/tools.namespace 0.0-237
  org.clojure/java.classpath 0.3.0
  org.clojure/tools.reader 1.3.2
progrock/progrock 0.1.2
orchestra/orchestra 2020.07.12-1
org.tcrawley/dynapath 1.1.0
hawk/hawk 0.2.11
  net.incongru.watchservice/barbary-watchservice 1.0
    net.java.dev.jna/jna 3.2.2
meta-merge/meta-merge 1.0.0
```

And using an alias. Note that Kaocha deps are not included here, only uberdeps (which is what I understood should be happening when "replace whatever is in your deps.edn with uberdeps" is stated in the readme):

```bash
> clj -Sverbose -Srepro -Sdeps '{:aliases {:uberjar {:replace-deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}}}' -A:uberjar -Stree

version      = 1.10.1.727
install_dir  = /usr/local/Cellar/clojure/1.10.1.727
config_dir   = /Users/ikoszo/.clojure
config_paths = /usr/local/Cellar/clojure/1.10.1.727/deps.edn deps.edn
cache_dir    = .cpcache
cp_file      = .cpcache/1480073956.cp

Refreshing classpath
DEPRECATED: Libs must be qualified, change aero => aero/aero (deps.edn)
DEPRECATED: Libs must be qualified, change orchestra => orchestra/orchestra (deps.edn)
DEPRECATED: Libs must be qualified, change slingshot => slingshot/slingshot (deps.edn)
DEPRECATED: Libs must be qualified, change meta-merge => meta-merge/meta-merge (deps.edn)
DEPRECATED: Libs must be qualified, change hawk => hawk/hawk (deps.edn)
DEPRECATED: Libs must be qualified, change progrock => progrock/progrock (deps.edn)
DEPRECATED: Libs must be qualified, change expound => expound/expound (deps.edn)
org.clojure/clojure 1.10.1
  org.clojure/core.specs.alpha 0.2.44
  org.clojure/spec.alpha 0.2.176
uberdeps/uberdeps 1.0.2
  org.clojure/tools.deps.alpha 0.9.782
    javax.inject/javax.inject 1
    com.cognitect.aws/api 0.8.408
      org.clojure/data.json 0.2.7
      commons-codec/commons-codec 1.13
      org.clojure/tools.logging 0.5.0
      com.cognitect/http-client 0.1.101
        org.eclipse.jetty/jetty-http 9.4.15.v20190215
          org.eclipse.jetty/jetty-io 9.4.15.v20190215
        org.eclipse.jetty/jetty-util 9.4.15.v20190215
        org.eclipse.jetty/jetty-client 9.4.15.v20190215
      org.clojure/core.async 0.5.527
        org.clojure/tools.analyzer.jvm 0.7.2
          org.clojure/tools.analyzer 0.6.9
          org.clojure/tools.reader 1.0.0-beta4
          org.clojure/core.memoize 0.5.9
            org.clojure/core.cache 0.6.5
              org.clojure/data.priority-map 0.0.7
          org.ow2.asm/asm-all 4.2
    com.cognitect.aws/endpoints 1.1.11.705
    org.clojure/tools.cli 1.0.194
    org.apache.maven.resolver/maven-resolver-transport-http 1.4.1
      org.slf4j/jcl-over-slf4j 1.7.25
      org.apache.httpcomponents/httpcore 4.4.10
      org.apache.httpcomponents/httpclient 4.5.6
    org.apache.maven.resolver/maven-resolver-transport-file 1.4.1
    org.apache.maven/maven-core 3.6.3
      org.codehaus.plexus/plexus-component-annotations 2.1.0
      org.apache.commons/commons-lang3 3.8.1
      org.apache.maven/maven-model-builder 3.6.3
        org.codehaus.plexus/plexus-interpolation 1.25
      org.codehaus.plexus/plexus-utils 3.2.1
      org.eclipse.sisu/org.eclipse.sisu.plexus 0.3.4
        javax.enterprise/cdi-api 1.0
          javax.annotation/jsr250-api 1.0
      org.apache.maven/maven-settings-builder 3.6.3
        org.sonatype.plexus/plexus-sec-dispatcher 1.4
          org.sonatype.plexus/plexus-cipher 1.4
      org.apache.maven/maven-settings 3.6.3
      org.apache.maven.shared/maven-shared-utils 3.2.1
        commons-io/commons-io 2.5
      org.codehaus.plexus/plexus-classworlds 2.6.0
      com.google.inject/guice$no_aop 4.2.1
        com.google.guava/guava 25.1-android
          com.google.errorprone/error_prone_annotations 2.1.3
          org.codehaus.mojo/animal-sniffer-annotations 1.14
          org.checkerframework/checker-compat-qual 2.0.0
          com.google.j2objc/j2objc-annotations 1.1
          com.google.code.findbugs/jsr305 3.0.2
        aopalliance/aopalliance 1.0
      org.apache.maven/maven-model 3.6.3
      org.eclipse.sisu/org.eclipse.sisu.inject 0.3.4
      org.apache.maven/maven-repository-metadata 3.6.3
      org.apache.maven/maven-builder-support 3.6.3
      org.apache.maven/maven-plugin-api 3.6.3
      org.apache.maven/maven-artifact 3.6.3
    org.apache.maven.resolver/maven-resolver-api 1.4.1
    org.apache.maven/maven-resolver-provider 3.6.3
      org.slf4j/slf4j-api 1.7.29
    org.clojure/data.xml 0.2.0-alpha6
      org.clojure/data.codec 0.1.0
    org.apache.maven.resolver/maven-resolver-spi 1.4.1
    org.clojure/tools.gitlibs 1.0.100
      com.jcraft/jsch.agentproxy.jsch 0.0.9
        com.jcraft/jsch.agentproxy.core 0.0.9
      org.eclipse.jgit/org.eclipse.jgit 4.10.0.201712302008-r
        com.googlecode.javaewah/JavaEWAH 1.1.6
        com.jcraft/jsch 0.1.54
      com.jcraft/jzlib 1.1.3
      com.jcraft/jsch.agentproxy.connector-factory 0.0.9
        com.jcraft/jsch.agentproxy.sshagent 0.0.9
        com.jcraft/jsch.agentproxy.usocket-jna 0.0.9
          net.java.dev.jna/jna 4.1.0
          net.java.dev.jna/jna-platform 4.1.0
        com.jcraft/jsch.agentproxy.pageant 0.0.9
        com.jcraft/jsch.agentproxy.usocket-nc 0.0.9
    org.apache.maven.resolver/maven-resolver-connector-basic 1.4.1
    com.cognitect.aws/s3 784.2.593.0
    org.apache.maven.resolver/maven-resolver-impl 1.4.1
    org.apache.maven.resolver/maven-resolver-util 1.4.1
```

Lastly, let's look at the dependency tree with the current readme suggestion, where _both_ the Kaocha and uberdeps dependencies are included, despite the intention (having only uberdeps' dependencies should be enough and carry fewer possibilities of errors):

```bash
> clj -Sverbose -Srepro -Sdeps '{:deps {uberdeps/uberdeps {:mvn/version "1.0.2"}}}' -Stree
version      = 1.10.1.727
install_dir  = /usr/local/Cellar/clojure/1.10.1.727
config_dir   = /Users/ikoszo/.clojure
config_paths = /usr/local/Cellar/clojure/1.10.1.727/deps.edn deps.edn
cache_dir    = .cpcache
cp_file      = .cpcache/2271716657.cp

Refreshing classpath
DEPRECATED: Libs must be qualified, change aero => aero/aero (deps.edn)
DEPRECATED: Libs must be qualified, change orchestra => orchestra/orchestra (deps.edn)
DEPRECATED: Libs must be qualified, change slingshot => slingshot/slingshot (deps.edn)
DEPRECATED: Libs must be qualified, change meta-merge => meta-merge/meta-merge (deps.edn)
DEPRECATED: Libs must be qualified, change hawk => hawk/hawk (deps.edn)
DEPRECATED: Libs must be qualified, change progrock => progrock/progrock (deps.edn)
DEPRECATED: Libs must be qualified, change expound => expound/expound (deps.edn)
org.clojure/clojure 1.10.1
  org.clojure/core.specs.alpha 0.2.44
expound/expound 0.8.5
org.clojure/spec.alpha 0.2.187
org.clojure/tools.cli 1.0.194
lambdaisland/deep-diff 0.0-47
  mvxcvi/puget 1.1.2
  fipp/fipp 0.6.17
  mvxcvi/arrangement 1.2.0
  org.clojure/core.rrb-vector 0.0.14
  tech.droit/clj-diff 1.0.1
slingshot/slingshot 0.12.2
aero/aero 1.1.6
lambdaisland/tools.namespace 0.0-237
  org.clojure/java.classpath 0.3.0
  org.clojure/tools.reader 1.3.2
progrock/progrock 0.1.2
orchestra/orchestra 2020.07.12-1
org.tcrawley/dynapath 1.1.0
hawk/hawk 0.2.11
  net.incongru.watchservice/barbary-watchservice 1.0
uberdeps/uberdeps 1.0.2
  org.clojure/tools.deps.alpha 0.9.782
    javax.inject/javax.inject 1
    com.cognitect.aws/api 0.8.408
      org.clojure/data.json 0.2.7
      commons-codec/commons-codec 1.13
      org.clojure/tools.logging 0.5.0
      com.cognitect/http-client 0.1.101
        org.eclipse.jetty/jetty-http 9.4.15.v20190215
          org.eclipse.jetty/jetty-io 9.4.15.v20190215
        org.eclipse.jetty/jetty-util 9.4.15.v20190215
        org.eclipse.jetty/jetty-client 9.4.15.v20190215
      org.clojure/core.async 0.5.527
        org.clojure/tools.analyzer.jvm 0.7.2
          org.clojure/tools.analyzer 0.6.9
          org.clojure/core.memoize 0.5.9
            org.clojure/core.cache 0.6.5
              org.clojure/data.priority-map 0.0.7
          org.ow2.asm/asm-all 4.2
    com.cognitect.aws/endpoints 1.1.11.705
    org.apache.maven.resolver/maven-resolver-transport-http 1.4.1
      org.slf4j/jcl-over-slf4j 1.7.25
      org.apache.httpcomponents/httpcore 4.4.10
      org.apache.httpcomponents/httpclient 4.5.6
    org.apache.maven.resolver/maven-resolver-transport-file 1.4.1
    org.apache.maven/maven-core 3.6.3
      org.codehaus.plexus/plexus-component-annotations 2.1.0
      org.apache.commons/commons-lang3 3.8.1
      org.apache.maven/maven-model-builder 3.6.3
        org.codehaus.plexus/plexus-interpolation 1.25
      org.codehaus.plexus/plexus-utils 3.2.1
      org.eclipse.sisu/org.eclipse.sisu.plexus 0.3.4
        javax.enterprise/cdi-api 1.0
          javax.annotation/jsr250-api 1.0
      org.apache.maven/maven-settings-builder 3.6.3
        org.sonatype.plexus/plexus-sec-dispatcher 1.4
          org.sonatype.plexus/plexus-cipher 1.4
      org.apache.maven/maven-settings 3.6.3
      org.apache.maven.shared/maven-shared-utils 3.2.1
        commons-io/commons-io 2.5
      org.codehaus.plexus/plexus-classworlds 2.6.0
      com.google.inject/guice$no_aop 4.2.1
        com.google.guava/guava 25.1-android
          com.google.errorprone/error_prone_annotations 2.1.3
          org.codehaus.mojo/animal-sniffer-annotations 1.14
          org.checkerframework/checker-compat-qual 2.0.0
          com.google.j2objc/j2objc-annotations 1.1
          com.google.code.findbugs/jsr305 3.0.2
        aopalliance/aopalliance 1.0
      org.apache.maven/maven-model 3.6.3
      org.eclipse.sisu/org.eclipse.sisu.inject 0.3.4
      org.apache.maven/maven-repository-metadata 3.6.3
      org.apache.maven/maven-builder-support 3.6.3
      org.apache.maven/maven-plugin-api 3.6.3
      org.apache.maven/maven-artifact 3.6.3
    org.apache.maven.resolver/maven-resolver-api 1.4.1
    org.apache.maven/maven-resolver-provider 3.6.3
      org.slf4j/slf4j-api 1.7.29
    org.clojure/data.xml 0.2.0-alpha6
      org.clojure/data.codec 0.1.0
    org.apache.maven.resolver/maven-resolver-spi 1.4.1
    org.clojure/tools.gitlibs 1.0.100
      com.jcraft/jsch.agentproxy.jsch 0.0.9
        com.jcraft/jsch.agentproxy.core 0.0.9
      org.eclipse.jgit/org.eclipse.jgit 4.10.0.201712302008-r
        com.googlecode.javaewah/JavaEWAH 1.1.6
        com.jcraft/jsch 0.1.54
      com.jcraft/jzlib 1.1.3
      com.jcraft/jsch.agentproxy.connector-factory 0.0.9
        com.jcraft/jsch.agentproxy.sshagent 0.0.9
        com.jcraft/jsch.agentproxy.usocket-jna 0.0.9
          net.java.dev.jna/jna 4.1.0
          net.java.dev.jna/jna-platform 4.1.0
        com.jcraft/jsch.agentproxy.pageant 0.0.9
        com.jcraft/jsch.agentproxy.usocket-nc 0.0.9
    org.apache.maven.resolver/maven-resolver-connector-basic 1.4.1
    com.cognitect.aws/s3 784.2.593.0
    org.apache.maven.resolver/maven-resolver-impl 1.4.1
    org.apache.maven.resolver/maven-resolver-util 1.4.1
meta-merge/meta-merge 1.0.0
```

**Comment by tonsky** [comment]
Thank you for the explanation! Seems like deps.edn are too complex for my understanding :)

**Comment by imrekoszo** [comment]
Tell me about it :) We believe we just found another one that happens when... 🥁  deps.edn is a symlink pointing to a file in another folder. I'm just creating a repro case, will submit issue and hopefully a PR.

**Pull request merged**
